[2022-12-21T20:32:17.344+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion_aws_dag.unzip_pgn manual__2022-12-21T20:27:00.001464+00:00 [queued]>
[2022-12-21T20:32:17.357+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion_aws_dag.unzip_pgn manual__2022-12-21T20:27:00.001464+00:00 [queued]>
[2022-12-21T20:32:17.357+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-21T20:32:17.357+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2022-12-21T20:32:17.357+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-21T20:32:17.383+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_pgn> on 2022-12-21 20:27:00.001464+00:00
[2022-12-21T20:32:17.390+0000] {standard_task_runner.py:55} INFO - Started process 1132 to run task
[2022-12-21T20:32:17.395+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_aws_dag', 'unzip_pgn', 'manual__2022-12-21T20:27:00.001464+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_aws_dag.py', '--cfg-path', '/tmp/tmp8hflkgti']
[2022-12-21T20:32:17.395+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask unzip_pgn
[2022-12-21T20:32:17.482+0000] {task_command.py:389} INFO - Running <TaskInstance: data_ingestion_aws_dag.unzip_pgn manual__2022-12-21T20:27:00.001464+00:00 [running]> on host 5850be76801c
[2022-12-21T20:32:17.647+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_aws_dag
AIRFLOW_CTX_TASK_ID=unzip_pgn
AIRFLOW_CTX_EXECUTION_DATE=2022-12-21T20:27:00.001464+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-21T20:27:00.001464+00:00
[2022-12-21T20:32:17.648+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-21T20:32:17.649+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'unzstd /opt/***/lichess_db_standard_rated_2013-01.pgn.zst > /opt/***/2013-01.pgn']
[2022-12-21T20:32:17.663+0000] {subprocess.py:86} INFO - Output:
[2022-12-21T20:32:17.666+0000] {subprocess.py:93} INFO - /bin/bash: line 1: unzstd: command not found
[2022-12-21T20:32:17.667+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-12-21T20:32:17.687+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-12-21T20:32:17.694+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=data_ingestion_aws_dag, task_id=unzip_pgn, execution_date=20221221T202700, start_date=20221221T203217, end_date=20221221T203217
[2022-12-21T20:32:17.726+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task unzip_pgn (Bash command failed. The command returned a non-zero exit code 127.; 1132)
[2022-12-21T20:32:17.766+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-21T20:32:17.791+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
