[2022-12-21T23:30:09.753+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion_aws_dag.ingest_pgn_task manual__2022-12-21T23:29:51.880612+00:00 [queued]>
[2022-12-21T23:30:09.770+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion_aws_dag.ingest_pgn_task manual__2022-12-21T23:29:51.880612+00:00 [queued]>
[2022-12-21T23:30:09.770+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-21T23:30:09.771+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-21T23:30:09.771+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-21T23:30:09.805+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): ingest_pgn_task> on 2022-12-21 23:29:51.880612+00:00
[2022-12-21T23:30:09.811+0000] {standard_task_runner.py:55} INFO - Started process 1388 to run task
[2022-12-21T23:30:09.815+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_aws_dag', 'ingest_pgn_task', 'manual__2022-12-21T23:29:51.880612+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_aws_dag.py', '--cfg-path', '/tmp/tmpvwxaaemi']
[2022-12-21T23:30:09.815+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask ingest_pgn_task
[2022-12-21T23:30:09.905+0000] {task_command.py:389} INFO - Running <TaskInstance: data_ingestion_aws_dag.ingest_pgn_task manual__2022-12-21T23:29:51.880612+00:00 [running]> on host ea0ded0d1b3f
[2022-12-21T23:30:10.087+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_aws_dag
AIRFLOW_CTX_TASK_ID=ingest_pgn_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-21T23:29:51.880612+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-21T23:29:51.880612+00:00
[2022-12-21T23:30:11.087+0000] {base.py:73} INFO - Using connection ID 'aws-postgres-chess-data' for task execution.
[2022-12-21T23:30:12.118+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_aws_dag.py", line 56, in ingest_pgn
    pgn = chess.pgn.read_game(f)
AttributeError: module 'chess' has no attribute 'pgn'
[2022-12-21T23:30:12.144+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_aws_dag, task_id=ingest_pgn_task, execution_date=20221221T232951, start_date=20221221T233009, end_date=20221221T233012
[2022-12-21T23:30:13.204+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 46 for task ingest_pgn_task (module 'chess' has no attribute 'pgn'; 1388)
[2022-12-21T23:30:13.246+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-21T23:30:13.271+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
