[2022-12-21T20:41:15.388+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion_aws_dag.unzip_pgn manual__2022-12-21T20:41:01.501505+00:00 [queued]>
[2022-12-21T20:41:15.418+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion_aws_dag.unzip_pgn manual__2022-12-21T20:41:01.501505+00:00 [queued]>
[2022-12-21T20:41:15.419+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-21T20:41:15.419+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-21T20:41:15.419+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-21T20:41:15.468+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): unzip_pgn> on 2022-12-21 20:41:01.501505+00:00
[2022-12-21T20:41:15.473+0000] {standard_task_runner.py:55} INFO - Started process 127 to run task
[2022-12-21T20:41:15.477+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_aws_dag', 'unzip_pgn', 'manual__2022-12-21T20:41:01.501505+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_aws_dag.py', '--cfg-path', '/tmp/tmp9flo3a67']
[2022-12-21T20:41:15.478+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask unzip_pgn
[2022-12-21T20:41:15.618+0000] {task_command.py:389} INFO - Running <TaskInstance: data_ingestion_aws_dag.unzip_pgn manual__2022-12-21T20:41:01.501505+00:00 [running]> on host 5805c7087eed
[2022-12-21T20:41:15.758+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_aws_dag
AIRFLOW_CTX_TASK_ID=unzip_pgn
AIRFLOW_CTX_EXECUTION_DATE=2022-12-21T20:41:01.501505+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-21T20:41:01.501505+00:00
[2022-12-21T20:41:15.759+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-21T20:41:15.760+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'unzstd /opt/***/lichess_db_standard_rated_2013-01.pgn.zst > /opt/***/2013-01.pgn']
[2022-12-21T20:41:15.776+0000] {subprocess.py:86} INFO - Output:
[2022-12-21T20:41:15.781+0000] {subprocess.py:93} INFO - /bin/bash: line 1: unzstd: command not found
[2022-12-21T20:41:15.782+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-12-21T20:41:15.798+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-12-21T20:41:15.803+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_aws_dag, task_id=unzip_pgn, execution_date=20221221T204101, start_date=20221221T204115, end_date=20221221T204115
[2022-12-21T20:41:16.220+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task unzip_pgn (Bash command failed. The command returned a non-zero exit code 127.; 127)
[2022-12-21T20:41:16.254+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-21T20:41:16.313+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
